version: '3.9'

services:
  app:
    build: .
    container_name: nest-app
    restart: always
    env_file: .env
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    # Hapus volumes bind
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    command: >
      sh -c "npx prisma migrate deploy &&
             node dist/main.js"
